const SUPABASE_URL = 'https://lpizyydqhxxnyvxhqbnj.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwaXp5eWRxaHh4bnl2eGhxYm5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkyMDY0NDgsImV4cCI6MjEwNDc4MjQ0OH0.GVmzLzaeCRPQ609mSde9AuTeuiUPm0eEYZkMKp2SXEA';

const supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
